name: Xcode - Build and Analyze

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: XcodeLegacy
        run: |
          sudo xcode-select -s /Applications/Xcode.app
          mkdir XcodeLegacy
          cd XcodeLegacy
          curl -O https://raw.githubusercontent.com/devernay/xcodelegacy/master/XcodeLegacy.sh
          curl -L https://github.com/tellowkrinkle/DLBuildTools/releases/download/v0.1/DLBuildTools.tar | tar -x
          sudo bash XcodeLegacy.sh -compilers -osx105 -osx107 install
      - name: Build
        run: xcodebuild clean build && exit ${PIPESTATUS[0]}
