name: Xcode - Build and Analyze

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: XcodeLegacy
        run: |
          sudo xcode-select -s /Applications/Xcode_11.7.app
          mkdir XcodeLegacy
          cd XcodeLegacy
          curl -O https://raw.githubusercontent.com/devernay/xcodelegacy/master/XcodeLegacy.sh
          curl -L https://github.com/tellowkrinkle/DLBuildTools/releases/download/v0.1/DLBuildTools.tar | tar -x
          sudo bash XcodeLegacy.sh -compilers -osx105 -osx107 -path=/Applications/Xcode_11.7.app install
      - name: Build
        run: |
          # Need to use legacy build system: https://github.com/devernay/xcodelegacy/issues/49
          cat > Discord\ Lite.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
                  <key>BuildSystemType</key>
                  <string>Original</string>
          </dict>
          </plist>
          EOF

          xcodebuild ARCHS="ppc x86_64" clean build && exit ${PIPESTATUS[0]}
